"""Every OS-specific bit of ClipboardHistory lives here (IS_MACOS / IS_WINDOWS).

Do not add sys.platform checks elsewhere: the rest of the app is plain Qt.
Same rule as ScreenCapture, same reason - one codebase for both laptops.

What this module covers:
    data_dir()                  where history + images are stored
    clipboard_sequence()        cheap "did the clipboard change" counter
    clipboard_is_private()      password-manager / transient flags -> skip
    write_text/image/files()    put an item back on the clipboard (native
                                on macOS so every app can paste it)
    remember_front_app()        who had focus before the panel opened
    restore_front_app(token)    give it focus back
    send_paste_keystroke()      simulate Cmd+V / Ctrl+V
    can_send_keystrokes()       macOS Accessibility permission check
    prepare_panel_window()      floating, non-activating, all-Spaces panel
    startup_enabled/set_...()   launch at login (LaunchAgent / Startup lnk)
"""
import os
import sys
import time

IS_MACOS = sys.platform == "darwin"
IS_WINDOWS = sys.platform == "win32"

APP_NAME = "ClipboardHistory"
BUNDLE_ID = "com.clipboardhistory.app"
SYSTEM_FONT = ".AppleSystemUIFont" if IS_MACOS else ("Segoe UI" if IS_WINDOWS else "Sans Serif")
PASTE_MODIFIER_LABEL = "Cmd" if IS_MACOS else "Ctrl"

if IS_WINDOWS:
    import ctypes
    import ctypes.wintypes


# ---------------------------------------------------------------------------
# Folders
# ---------------------------------------------------------------------------

def data_dir():
    """Per-user folder for history.json and the images/ subfolder.
    Env CLIPBOARDHISTORY_DATA_DIR overrides it (tests, side-by-side copies)."""
    override = os.environ.get("CLIPBOARDHISTORY_DATA_DIR")
    if override:
        os.makedirs(os.path.join(override, "images"), exist_ok=True)
        return override
    if IS_MACOS:
        base = os.path.expanduser("~/Library/Application Support")
    elif IS_WINDOWS:
        base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
    else:
        base = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
    path = os.path.join(base, APP_NAME)
    os.makedirs(os.path.join(path, "images"), exist_ok=True)
    return path


def open_folder(path):
    try:
        import subprocess
        if IS_MACOS:
            subprocess.Popen(["open", path])
        elif IS_WINDOWS:
            os.startfile(path)  # type: ignore[attr-defined]
        else:
            subprocess.Popen(["xdg-open", path])
    except Exception as e:
        print(f"open_folder: {e}")


# ---------------------------------------------------------------------------
# Clipboard change detection + privacy flags
# ---------------------------------------------------------------------------

def clipboard_sequence():
    """Monotonic counter that changes whenever the clipboard content changes.

    macOS: NSPasteboard changeCount. Windows: GetClipboardSequenceNumber.
    Elsewhere: None (the watcher falls back to Qt's dataChanged signal).
    """
    if IS_MACOS:
        try:
            from AppKit import NSPasteboard
            return int(NSPasteboard.generalPasteboard().changeCount())
        except Exception:
            return None
    if IS_WINDOWS:
        try:
            return int(ctypes.windll.user32.GetClipboardSequenceNumber())
        except Exception:
            return None
    return None


def clipboard_is_private():
    """True when the current clipboard content asks not to be recorded.

    Password managers (1Password, Bitwarden...) flag their copies:
    macOS  - org.nspasteboard.ConcealedType / TransientType
    Windows - the ExcludeClipboardContentFromMonitorProcessing format
    """
    if IS_MACOS:
        try:
            from AppKit import NSPasteboard
            types = set(NSPasteboard.generalPasteboard().types() or [])
            return bool(types & {"org.nspasteboard.ConcealedType",
                                 "org.nspasteboard.TransientType",
                                 "org.nspasteboard.AutoGeneratedType"})
        except Exception:
            return False
    if IS_WINDOWS:
        try:
            user32 = ctypes.windll.user32
            fmt = user32.RegisterClipboardFormatW("ExcludeClipboardContentFromMonitorProcessing")
            return bool(fmt and user32.IsClipboardFormatAvailable(fmt))
        except Exception:
            return False
    return False


# ---------------------------------------------------------------------------
# Writing items back to the clipboard
# ---------------------------------------------------------------------------

def write_text(text):
    """Plain text -> clipboard."""
    if IS_MACOS:
        try:
            from AppKit import NSPasteboard, NSPasteboardTypeString
            pb = NSPasteboard.generalPasteboard()
            pb.clearContents()
            pb.setString_forType_(text, NSPasteboardTypeString)
            return True
        except Exception as e:
            print(f"write_text (native): {e}")
    from PyQt6.QtWidgets import QApplication
    QApplication.clipboard().setText(text)
    return True


def write_image(png_bytes):
    """PNG bytes -> clipboard. macOS publishes TIFF + PNG through NSImage so
    Mail, Pages, Slack, Photoshop... all accept the paste."""
    if IS_MACOS:
        try:
            from AppKit import NSPasteboard, NSImage
            from Foundation import NSData
            data = NSData.dataWithBytes_length_(png_bytes, len(png_bytes))
            img = NSImage.alloc().initWithData_(data)
            pb = NSPasteboard.generalPasteboard()
            pb.clearContents()
            if img is not None and pb.writeObjects_([img]):
                return True
        except Exception as e:
            print(f"write_image (native): {e}")
    from PyQt6.QtWidgets import QApplication
    from PyQt6.QtGui import QImage
    img = QImage.fromData(png_bytes, "PNG")
    QApplication.clipboard().setImage(img)
    return True


def write_files(paths):
    """List of file paths -> clipboard (Finder / Explorer can paste them)."""
    paths = [p for p in paths if os.path.exists(p)]
    if not paths:
        return False
    if IS_MACOS:
        try:
            from AppKit import NSPasteboard
            from Foundation import NSURL
            pb = NSPasteboard.generalPasteboard()
            pb.clearContents()
            urls = [NSURL.fileURLWithPath_(p) for p in paths]
            if pb.writeObjects_(urls):
                return True
        except Exception as e:
            print(f"write_files (native): {e}")
    from PyQt6.QtWidgets import QApplication
    from PyQt6.QtCore import QMimeData, QUrl
    mime = QMimeData()
    mime.setUrls([QUrl.fromLocalFile(p) for p in paths])
    mime.setText("\n".join(paths))
    QApplication.clipboard().setMimeData(mime)
    return True


# ---------------------------------------------------------------------------
# Focus hand-off + simulated paste
# ---------------------------------------------------------------------------

def remember_front_app():
    """Opaque token for the app/window that had focus when the hotkey fired."""
    if IS_MACOS:
        try:
            from AppKit import NSWorkspace
            return NSWorkspace.sharedWorkspace().frontmostApplication()
        except Exception:
            return None
    if IS_WINDOWS:
        try:
            return int(ctypes.windll.user32.GetForegroundWindow())
        except Exception:
            return None
    return None


def front_app_name(token=None):
    """Human name of the app behind a remember_front_app() token (or the
    current frontmost app when token is None)."""
    if token is None:
        token = remember_front_app()
    if token is None:
        return ""
    if IS_MACOS:
        try:
            return str(token.localizedName() or "")
        except Exception:
            return ""
    if IS_WINDOWS:
        try:
            pid = ctypes.wintypes.DWORD()
            ctypes.windll.user32.GetWindowThreadProcessId(token, ctypes.byref(pid))
            h = ctypes.windll.kernel32.OpenProcess(0x1000, False, pid.value)  # QUERY_LIMITED_INFORMATION
            if not h:
                return ""
            buf = ctypes.create_unicode_buffer(1024)
            size = ctypes.wintypes.DWORD(1024)
            ok = ctypes.windll.kernel32.QueryFullProcessImageNameW(h, 0, buf, ctypes.byref(size))
            ctypes.windll.kernel32.CloseHandle(h)
            if ok:
                return os.path.splitext(os.path.basename(buf.value))[0]
        except Exception:
            pass
    return ""


def restore_front_app(token):
    """Give focus back to the app captured by remember_front_app()."""
    if token is None:
        return
    if IS_MACOS:
        try:
            # NSApplicationActivateIgnoringOtherApps = 1 << 1
            token.activateWithOptions_(1 << 1)
        except Exception as e:
            print(f"restore_front_app: {e}")
    elif IS_WINDOWS:
        try:
            user32 = ctypes.windll.user32
            kernel32 = ctypes.windll.kernel32
            fg = user32.GetForegroundWindow()
            cur_tid = kernel32.GetCurrentThreadId()
            fg_tid = user32.GetWindowThreadProcessId(fg, None) if fg else 0
            attached = False
            if fg_tid and fg_tid != cur_tid:
                attached = bool(user32.AttachThreadInput(fg_tid, cur_tid, True))
            try:
                user32.SetForegroundWindow(token)
            finally:
                if attached:
                    user32.AttachThreadInput(fg_tid, cur_tid, False)
        except Exception as e:
            print(f"restore_front_app: {e}")


def can_send_keystrokes():
    """macOS needs the Accessibility permission to post a Cmd+V keystroke.
    Windows needs nothing."""
    if not IS_MACOS:
        return True
    try:
        import ctypes as _ct
        import ctypes.util
        ax = _ct.CDLL(_ct.util.find_library("ApplicationServices"))
        ax.AXIsProcessTrusted.restype = _ct.c_bool
        return bool(ax.AXIsProcessTrusted())
    except Exception:
        return False


def request_keystroke_permission():
    """Show the macOS Accessibility prompt / open the settings pane."""
    if not IS_MACOS:
        return
    try:
        from ApplicationServices import AXIsProcessTrustedWithOptions, kAXTrustedCheckOptionPrompt
        AXIsProcessTrustedWithOptions({kAXTrustedCheckOptionPrompt: True})
    except Exception:
        pass
    try:
        import subprocess
        subprocess.Popen(["open",
                          "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"],
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass


def send_paste_keystroke():
    """Type Cmd+V (macOS) / Ctrl+V (Windows) into the focused app.
    Returns False when it could not be sent (no permission)."""
    if IS_MACOS:
        if not can_send_keystrokes():
            return False
        try:
            from Quartz import (
                CGEventCreateKeyboardEvent, CGEventPost, CGEventSetFlags,
                kCGHIDEventTap, kCGEventFlagMaskCommand,
            )
            kVK_V = 9
            down = CGEventCreateKeyboardEvent(None, kVK_V, True)
            up = CGEventCreateKeyboardEvent(None, kVK_V, False)
            CGEventSetFlags(down, kCGEventFlagMaskCommand)
            CGEventSetFlags(up, kCGEventFlagMaskCommand)
            CGEventPost(kCGHIDEventTap, down)
            time.sleep(0.01)
            CGEventPost(kCGHIDEventTap, up)
            return True
        except Exception as e:
            print(f"send_paste_keystroke: {e}")
            return False
    if IS_WINDOWS:
        try:
            user32 = ctypes.windll.user32
            VK_CONTROL, VK_V, KEYEVENTF_KEYUP = 0x11, 0x56, 0x0002
            # Release modifiers the user may still be holding from the hotkey
            # (Ctrl+Shift+V) so the app sees a clean Ctrl+V.
            for vk in (0x10, 0x12, 0x5B):  # Shift, Alt, LWin
                if user32.GetAsyncKeyState(vk) & 0x8000:
                    user32.keybd_event(vk, 0, KEYEVENTF_KEYUP, 0)
            user32.keybd_event(VK_CONTROL, 0, 0, 0)
            user32.keybd_event(VK_V, 0, 0, 0)
            user32.keybd_event(VK_V, 0, KEYEVENTF_KEYUP, 0)
            user32.keybd_event(VK_CONTROL, 0, KEYEVENTF_KEYUP, 0)
            return True
        except Exception as e:
            print(f"send_paste_keystroke: {e}")
            return False
    return False


def modifiers_released():
    """True once the user let go of Cmd/Ctrl/Shift after the hotkey. Sending
    Cmd+V while Shift is still down would paste-without-formatting or nothing."""
    if IS_MACOS:
        try:
            from AppKit import NSEvent
            flags = int(NSEvent.modifierFlags())
            # shift 1<<17, control 1<<18, option 1<<19, command 1<<20
            return not (flags & ((1 << 17) | (1 << 18) | (1 << 19) | (1 << 20)))
        except Exception:
            return True
    if IS_WINDOWS:
        try:
            user32 = ctypes.windll.user32
            for vk in (0x10, 0x11, 0x12, 0x5B, 0x5C):
                if user32.GetAsyncKeyState(vk) & 0x8000:
                    return False
            return True
        except Exception:
            return True
    return True


# ---------------------------------------------------------------------------
# The floating panel window
# ---------------------------------------------------------------------------

def prepare_panel_window(widget):
    """Make the popup float above everything, on every Space / desktop,
    without stealing the previous app's activation. Call after the widget
    exists (create()) and before show().

    macOS: NSPanel with the non-activating mask at level 25, joins all
    Spaces. Keyboard focus still works (makeKeyAndOrderFront in show_panel).
    Windows: nothing native needed; the panel activates normally and the
    previous window is restored with restore_front_app() when pasting.
    """
    if not IS_MACOS:
        return
    try:
        import ctypes as _ct
        import objc
        from AppKit import (
            NSWindowCollectionBehaviorCanJoinAllSpaces,
            NSWindowCollectionBehaviorStationary,
            NSWindowCollectionBehaviorIgnoresCycle,
            NSWindowCollectionBehaviorFullScreenAuxiliary,
            NSWindowCollectionBehaviorTransient,
            NSWindowStyleMaskNonactivatingPanel,
        )
        widget.create()
        ptr = int(widget.winId())
        if ptr == 0:
            return
        nsview = objc.objc_object(c_void_p=_ct.c_void_p(ptr))
        nswindow = nsview.window()
        if nswindow is None:
            return
        nswindow.setLevel_(25)
        nswindow.setHidesOnDeactivate_(False)
        nswindow.setCollectionBehavior_(
            NSWindowCollectionBehaviorCanJoinAllSpaces
            | NSWindowCollectionBehaviorStationary
            | NSWindowCollectionBehaviorIgnoresCycle
            | NSWindowCollectionBehaviorFullScreenAuxiliary
            | NSWindowCollectionBehaviorTransient
        )
        try:
            nswindow.setStyleMask_(int(nswindow.styleMask()) | NSWindowStyleMaskNonactivatingPanel)
        except Exception:
            pass
    except Exception as e:
        print(f"prepare_panel_window: {e}")


def focus_panel_window(widget):
    """Give the shown panel keyboard focus.

    macOS: makeKeyAndOrderFront on the non-activating panel is enough for
    typing; we deliberately do NOT activate our own app so the previous
    app keeps its activation and receives the Cmd+V later.
    """
    if IS_MACOS:
        try:
            import ctypes as _ct
            import objc
            ptr = int(widget.winId())
            nsview = objc.objc_object(c_void_p=_ct.c_void_p(ptr))
            nswindow = nsview.window()
            if nswindow is not None:
                nswindow.makeKeyAndOrderFront_(None)
        except Exception as e:
            print(f"focus_panel_window: {e}")
    elif IS_WINDOWS:
        try:
            user32 = ctypes.windll.user32
            kernel32 = ctypes.windll.kernel32
            hwnd = int(widget.winId())
            fg = user32.GetForegroundWindow()
            cur_tid = kernel32.GetCurrentThreadId()
            fg_tid = user32.GetWindowThreadProcessId(fg, None) if fg else 0
            attached = False
            if fg_tid and fg_tid != cur_tid:
                attached = bool(user32.AttachThreadInput(fg_tid, cur_tid, True))
            try:
                user32.BringWindowToTop(hwnd)
                user32.SetForegroundWindow(hwnd)
                user32.SetFocus(hwnd)
            finally:
                if attached:
                    user32.AttachThreadInput(fg_tid, cur_tid, False)
        except Exception as e:
            print(f"focus_panel_window: {e}")
    widget.activateWindow()


# ---------------------------------------------------------------------------
# Launch at login
# ---------------------------------------------------------------------------

def _launch_agent_path():
    return os.path.expanduser(f"~/Library/LaunchAgents/{BUNDLE_ID}.plist")


def _startup_link_windows():
    startup = os.path.join(os.environ.get("APPDATA", ""), "Microsoft", "Windows",
                           "Start Menu", "Programs", "Startup")
    return os.path.join(startup, f"{APP_NAME}.lnk")


def startup_enabled():
    if IS_MACOS:
        return os.path.exists(_launch_agent_path())
    if IS_WINDOWS:
        return os.path.exists(_startup_link_windows())
    return False


def set_startup_enabled(enabled, python_exe, main_py, icon_path=None):
    """macOS: LaunchAgent that runs `python_exe main_py` at login (and keeps
    it alive). Windows: shortcut in the Startup folder (pythonw.exe so no
    console window). Returns True on success."""
    if IS_MACOS:
        plist = _launch_agent_path()
        label = BUNDLE_ID
        try:
            import subprocess
            uid = os.getuid()
            if not enabled:
                subprocess.run(["launchctl", "bootout", f"gui/{uid}/{label}"],
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                if os.path.exists(plist):
                    os.remove(plist)
                return True
            os.makedirs(os.path.dirname(plist), exist_ok=True)
            workdir = os.path.dirname(os.path.abspath(main_py))
            with open(plist, "w", encoding="utf-8") as f:
                f.write(f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{python_exe}</string>
    <string>{main_py}</string>
  </array>
  <key>WorkingDirectory</key><string>{workdir}</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>StandardErrorPath</key><string>/tmp/clipboardhistory_agent.log</string>
  <key>StandardOutPath</key><string>/tmp/clipboardhistory_agent.log</string>
</dict></plist>
""")
            # Do not bootstrap here: the running process IS the app; the agent
            # takes over at next login (or `launchctl bootstrap` from a shell).
            return True
        except Exception as e:
            print(f"set_startup_enabled: {e}")
            return False
    if IS_WINDOWS:
        link = _startup_link_windows()
        try:
            if not enabled:
                if os.path.exists(link):
                    os.remove(link)
                return True
            exe = python_exe
            if exe.lower().endswith("python.exe"):
                cand = exe[:-len("python.exe")] + "pythonw.exe"
                if os.path.exists(cand):
                    exe = cand
            from win32com.client import Dispatch  # pywin32
            shell = Dispatch("WScript.Shell")
            sc = shell.CreateShortCut(link)
            sc.Targetpath = exe
            sc.Arguments = f'"{main_py}"'
            sc.WorkingDirectory = os.path.dirname(os.path.abspath(main_py))
            sc.Description = f"{APP_NAME} - auto start"
            if icon_path and os.path.exists(icon_path):
                sc.IconLocation = icon_path
            sc.save()
            return True
        except Exception as e:
            print(f"set_startup_enabled: {e}")
            return False
    return False


def set_process_identity():
    """Cosmetics: no Dock icon on macOS, 'ClipboardHistory' (not Python) as
    the toast / taskbar identity on Windows. Call before QApplication."""
    if IS_MACOS:
        try:
            import AppKit
            AppKit.NSBundle.mainBundle().infoDictionary()["LSUIElement"] = "1"
        except Exception:
            pass
    elif IS_WINDOWS:
        try:
            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("RMScience.ClipboardHistory")
        except Exception:
            pass


def pin_as_accessory_app():
    """macOS: menu-bar utility (no Dock icon, no app switcher entry)."""
    if IS_MACOS:
        try:
            import AppKit
            if AppKit.NSApp is not None:
                AppKit.NSApp.setActivationPolicy_(1)  # NSApplicationActivationPolicyAccessory
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Close the panel when the user clicks somewhere else
# ---------------------------------------------------------------------------

_click_monitor = None  # retained for the process lifetime


def install_outside_click_monitor(widget, callback):
    """Call callback() when the mouse is pressed anywhere outside `widget`
    while it is visible. Qt's WindowDeactivate covers most cases; on macOS a
    non-activating panel does not always get one, so a global NSEvent
    monitor for mouse-down (no permission needed for mouse events) is
    added as a safety net. No-op elsewhere."""
    global _click_monitor
    if not IS_MACOS:
        return
    try:
        from AppKit import NSEvent, NSEventMaskLeftMouseDown, NSEventMaskRightMouseDown

        def _handler(event):
            try:
                if widget.isVisible():
                    callback()
            except Exception as e:
                print(f"outside-click: {e}")

        _click_monitor = NSEvent.addGlobalMonitorForEventsMatchingMask_handler_(
            NSEventMaskLeftMouseDown | NSEventMaskRightMouseDown, _handler)
    except Exception as e:
        print(f"install_outside_click_monitor: {e}")
